# Override para desenvolvimento local
version: '3.8'

services:
  lotus-app:
    build: 
      context: .
      target: development
    volumes:
      - .:/var/www/lotus
      - ./propostas:/var/www/lotus/propostas
      - ./logs:/var/log/nginx
    environment:
      - NODE_ENV=development
      - DEBUG=true
    ports:
      - "3000:80"
      - "3001:8080"  # Porta de desenvolvimento


