version: '3.8'

services:
  # Aplicação principal Lotus
  lotus-app:
    build: .
    container_name: lotus-app
    ports:
      - "3000:80"
    volumes:
      - ./propostas:/var/www/lotus/propostas
      - ./logs:/var/log/nginx
      - lotus-storage:/var/www/storage
    environment:
      - NODE_ENV=production
      - WEBHOOK_URL=https://n8n.nexuso2.com/webhook-test/bc635618-3f64-4db0-950e-feefaa899344
    restart: unless-stopped
    networks:
      - lotus-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.lotus.rule=Host(`lotus.localhost`)"
      - "traefik.http.services.lotus.loadbalancer.server.port=80"

  # Banco de dados para N8N
  postgres:
    image: postgres:15-alpine
    container_name: lotus-postgres
    environment:
      - POSTGRES_USER=n8n
      - POSTGRES_PASSWORD=n8n_password
      - POSTGRES_DB=n8n
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      - lotus-network

  # Redis para cache (opcional)
  redis:
    image: redis:7-alpine
    container_name: lotus-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    networks:
      - lotus-network

  # Traefik para proxy reverso (opcional)
  traefik:
    image: traefik:v2.10
    container_name: lotus-traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"  # Dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - traefik-data:/data
    restart: unless-stopped
    networks:
      - lotus-network
    labels:
      - "traefik.enable=true"

  # File browser para gerenciar arquivos
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: lotus-filebrowser
    ports:
      - "8081:80"
    volumes:
      - lotus-storage:/srv
      - ./propostas:/srv/propostas
    environment:
      - FB_BASEURL=/files
    restart: unless-stopped
    networks:
      - lotus-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.filebrowser.rule=Host(`files.lotus.localhost`)"

  # Backup service
  backup:
    image: alpine:latest
    container_name: lotus-backup
    volumes:
      - lotus-storage:/data/storage
      - ./propostas:/data/propostas
      - ./backups:/backups
    command: >
      sh -c "
      while true; do
        echo 'Iniciando backup...'
        tar -czf /backups/lotus-backup-$(date +%Y%m%d-%H%M%S).tar.gz -C /data .
        echo 'Backup concluído: lotus-backup-$(date +%Y%m%d-%H%M%S).tar.gz'
        # Manter apenas os 10 backups mais recentes
        ls -t /backups/lotus-backup-*.tar.gz | tail -n +11 | xargs -r rm
        sleep 86400  # Backup diário
      done
      "
    restart: unless-stopped
    networks:
      - lotus-network

# Volumes persistentes
volumes:
  n8n-data:
    driver: local
  postgres-data:
    driver: local
  redis-data:
    driver: local
  lotus-storage:
    driver: local
  traefik-data:
    driver: local

# Rede interna
networks:
  lotus-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16