version: '3.8'

services:
  lotus-app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: lotus-propostas
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - REACT_EDITOR=""
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium
      # WhatsApp Configuration - Configure estas variáveis no Coolify
      - WAHA_URL=${WAHA_URL:-https://waha.nexuso2.com}
      - WAHA_API_KEY=${WAHA_API_KEY}
      - WHATSAPP_PHONE=${WHATSAPP_PHONE}
      - WHATSAPP_SESSION=${WHATSAPP_SESSION:-lotus}
    volumes:
      # Pasta para PDFs gerados (persistir dados)
      - ./propostas:/app/propostas
      - /etc/localtime:/etc/localtime:ro  # Sincronizar timezone
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000 || exit 1"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'
    networks:
      - lotus-network

networks:
  lotus-network:
    driver: bridge