version: '3.8'

services:
  lotus-app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: lotus-propostas
    ports:
      - "3000:3000"
    environment:
      # OBRIGATÓRIAS
      - NODE_ENV=production
      - JWT_SECRET_CURRENT=${JWT_SECRET_CURRENT}
      
      # Next.js
      - NEXT_TELEMETRY_DISABLED=1
      - REACT_EDITOR=""
      
      # Database (usando padrão local)
      # - DATABASE_URL=${DATABASE_URL:-sqlite:./database.sqlite}
      
      # Puppeteer/PDF
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium
      
      # WhatsApp (opcionais)
      - WAHA_URL=${WAHA_URL:-https://waha.nexuso2.com}
      - WAHA_API_KEY=${WAHA_API_KEY}
      - WHATSAPP_PHONE=${WHATSAPP_PHONE}
      - WHATSAPP_SESSION=${WHATSAPP_SESSION:-lotus}
    volumes:
      # Persistir dados
      - ./propostas:/app/propostas
      - ./database:/app/database
      - /etc/localtime:/etc/localtime:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/health || exit 1"]
      interval: 30s
      timeout: 15s
      retries: 5
      start_period: 60s
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'
    networks:
      - lotus-network

networks:
  lotus-network:
    driver: bridge