version: '3.8'

services:
  lotus-app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: lotus-propostas
    ports:
      - "3000:3000"
    environment:
      # OBRIGAT칍RIA - PostgreSQL Database
      - DATABASE_URL=${DATABASE_URL}
      
      # OBRIGAT칍RIA - Ambiente
      - NODE_ENV=production
      
      # Next.js otimiza칞칫es
      - NEXT_TELEMETRY_DISABLED=1
      - REACT_EDITOR=""
      
      # Coolify - Preven칞칚o de vari치veis conflitantes
      # Essas vari치veis s칚o automaticamente removidas pelo start-server.sh
      # para evitar conflitos com o dom칤nio personalizado
      
    volumes:
      # Volume para dados persistentes (se necess치rio no futuro)
      - lotus-data:/app/data
      - /etc/localtime:/etc/localtime:ro
      
    restart: unless-stopped
    
    # Health Check - Coolify compat칤vel
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000/api/health || exit 1"]
      interval: 30s
      timeout: 15s
      retries: 3
      start_period: 60s
      
    # Resource limits otimizados para Coolify
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'
          
    networks:
      - lotus-network

  # 丘멆잺 PostgreSQL N츾O inclu칤do pois Coolify usa PostgreSQL externo
  # DATABASE_URL deve apontar para a inst칙ncia PostgreSQL externa
  
volumes:
  # Volume para dados da aplica칞칚o (se necess치rio)
  lotus-data:
    driver: local

networks:
  lotus-network:
    driver: bridge

# 游늶 INSTRU칂칏ES PARA COOLIFY:
# 
# 1. Vari치veis de ambiente obrigat칩rias:
#    DATABASE_URL=postgres://postgres:password@host:5432/lotus
#    NODE_ENV=production
#
# 2. Health Check configurar no Coolify:
#    Path: /api/health
#    Method: GET
#    Expected Response: OK
#    Timeout: 60s
#
# 3. Domain: lt.odois.dev
#
# 4. Resources:
#    Memory: 512MB (reserved) / 1GB (limit)
#    CPU: 0.25 (reserved) / 0.5 (limit)
#
# 5. IMPORTANTE: O projeto remove automaticamente vari치veis
#    SERVICE_FQDN_* e SERVICE_URL_* do Coolify que causam conflitos