version: '3.8'

services:
  lotus-app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: lotus-propostas
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=true
      - PUPPETEER_EXECUTABLE_PATH=/usr/bin/chromium-browser
      # WhatsApp Configuration - Configure estas variáveis no Coolify
      - WAHA_URL=${WAHA_URL:-https://waha.nexuso2.com}
      - WAHA_API_KEY=${WAHA_API_KEY}
      - WHATSAPP_PHONE=${WHATSAPP_PHONE}
      - WHATSAPP_SESSION=${WHATSAPP_SESSION:-lotus}
    volumes:
      # Pasta para PDFs gerados (persistir dados)
      - ./propostas:/app/propostas
      - /etc/localtime:/etc/localtime:ro  # Sincronizar timezone
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'
    networks:
      - lotus-network

networks:
  lotus-network:
    driver: bridge